version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-username:username
    DOCKERHUB_TOKEN: dockerhub-token:token

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Docker..."
      - yum install -y docker
      - service docker start
      - docker info

  pre_build:
    commands:
      - echo "DockerHub Username Loaded"
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - cd product-service
      - mvn clean package -DskipTests
      - docker build -t $DOCKERHUB_USERNAME/product-service:latest .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $DOCKERHUB_USERNAME/product-service:latest

artifacts:
  files:
    - '**/*'
