version: 0.2

env:
  variables:
    IMAGE_TAG: latest
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-username:username
    DOCKERHUB_TOKEN: dockerhub-token:token

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - docker --version

  pre_build:
    commands:
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - cd product-service
      - mvn clean package -DskipTests
      - docker build -t $DOCKERHUB_USERNAME/product-service:$IMAGE_TAG .

  post_build:
    commands:
      - docker push $DOCKERHUB_USERNAME/product-service:$IMAGE_TAG
