version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo Building product-service Docker image
      - cd product-service
      - mvn clean package -DskipTests
      - docker build -t product-service:latest .
