apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginxApp
    env: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80 
